### ISSUE TITLE
Kustomize legacy ordering conflicts

### ISSUE THREAD

**Issue by seaneagan** [airshipit/airshipctl#154]
**Problem description (if applicable)**

Airshipctl is [currently using](https://github.com/airshipit/airshipctl/blob/6ea552bbbc71aa765ce07ac0db6b35d2cfb25390/pkg/document/bundle.go#L162) kustomize legacy ordering. This means that one no longer has control over the order of the document application to kubernetes

**Proposed change**

Remove the use of the legacy ordering and do the equivalent of `kustomize build --reorder none ...`.

This way kustomization authors can control the exact order of documents to resolve any ordering conflicts that arise.

**Potential impacts**

n/a

**Comment by ian-howell** [comment]
I believe this will be fixed here: https://review.opendev.org/#/c/715571/6/pkg/document/bundle.go

**Comment by teoyaomiqui** [comment]
> Airshipctl is currently using kustomize legacy ordering. This means that one no longer has control over the order of the document application to kubernetes
I don't think that is true, it is simply default order nothing else. Problem is different, it is that bundle interface doesn't provide any method to reorder it. So what i would imagine, that bundle user would build the bundle with default order, and then if wants, he would call Order(HowToOrder),  method, which is to be developed when we have understanding what order usecases we have.  I thought of adding this method, however there is really no usecase yet. When we will have it(order usecase other than kubernetes), i'd suggest to implement it via extending bundle interface, rather than trying to guess future usecases now., unless you bumped into one already.

**Comment by jezogwza** [comment]
We agree that we will make LegacyOrder default behavior, but can b bypassed via changes to kustomize options that the bundle will use.

**Comment by jezogwza** [comment]
Will close for now. If the reordering or special order use cases reappears will open a new issue.
