### ISSUE TITLE
Develop an airshipctl endpoints catalog

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#317]
**Problem description (if applicable)**
As an operator, I would like to have a mechanism for specifying non-OpenStack-Helm software/component endpoints for in a common place so I can manage the platform in a consist fashion. Additionally, I would like to have the ability to override an endpoint value at a lower type/site level.

**Proposed change**
1. Identify all function instances where software/component endpoints are being specified. OpenStack-Helm components should not be taken into consideration & will be handled under a separate issue. 
2. Based on the composite/phase approach, determine at what level the endpoint catalog should be specified. 
3. Create replacement rules that update the endpoint values into the respective functions.
4. See design 1/5/21 design meeting notes for sample endpoint format: https://hackmd.io/QiEksO4fRk-MnBjwBFaAkQ#Quick-revisit-of-Variable-Catalog-Open-issues
5. Provide the means for reconstructing the URL from the endpoint catalog component parts.

**Comment by jezogwza** [comment]
We will have a single endpoint catalogue that will not be strongly typed.
Will allow for formated data that comply with the HelmToolkit expectations for endpoint definitions.
such as 
  ceph_object_store:
      name: radosgw
      namespace: osh-infra
      hosts:
        default: ceph-rgw
        public: radosgw
      host_fqdn_override:
        default: null
      path:
        default: null
      scheme:
        default: "http"
      port:
        api:
          default: 8088
          public: 80


But will also allow for other formatted data that best suits the different HelmRelease documents.
Such as : 
      grafana:
         ingress:
           enabled: true
           **_hosts:
             - grafana-nc.rdm9a.cci.att.com_**

**Comment by mattmceuen** [comment]
I think we need to split this into three issues:
1 OpenStack-Helm: Create an endpoints catalogue based essentially 1:1 from Airship 1 endpoint catalogue, i.e. "helm-toolkit format".

2 Airship: Explore/grep the functions, looking for URLs/endpoints that are not already cared for by the network or versions catalogues, and which we expect to be different from site to site.  If necessary, create an endpoint catalogue + schema that matches the need here.

3. Treasuremap: Similar to #2, but with higher likelihood of need due to LMA functions (assuming LMA functions live in treasuremap).  It's likely that some endpoint information that was captured for LMA charts in Airship 1 in "helm-toolkit format" will be needed for the new LMA functions; however, most of them will not use helm-toolkit in Airship 2 and will therefore need a different representation.  Part of this issue will be to determine the endpoint format(s) required and to create a schema - perhaps a hybrid htk/non-htk schema or multiple schema - to represent it.

**Comment by demonCoder95** [comment]
I think this links with the wider issue #363 which suggests creating different ``VariableCatalog`` types. The type under discussion in this issue, say``EndpointVariableCatalog`` can be one Kind, or as @mattmceuen has suggested, we can have "oshEndpointVariableCatalog`` and ``AirshipEndpointVariableCatalog`` and so on. I suggest we proceed accordingly and update both issues going forward.

**Comment by ak3216** [comment]
See updates to Proposed Change from 1/5/21 design call. Updated with endpoint format example & new item to provide capability to construct the URL from the component parts. New issue will be created for OpenStack-Helm endpoint catalog.

**Comment by demonCoder95** [comment]
Will do, thanks for the update @ak3216 !

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by matthew-fuller** [comment]
It's looking like a dedicated EndpointCatalogue may not be necessary for airshipctl. In researching this issue, most endpoint / URL keys appear to already have replacements defined in our NetworkCatalogue. There are some keys like `localAPIEndpoint` defined in CRDs like KubeadmConfigTemplate, but they don't appear to be used.

The prometheus/monitor has a hardcoded endpoint path of `/metrics`, but it's using a k8s selector instead of an IP, and the `/metrics` endpoint doesn't look likely to change from site to site.

I haven't found a lot of endpoint URLs in treasuremap that aren't already covered with replacements from our current catalogues, but there may be a few, particularly in places like lma-infra, that could get replaced on a site to site basis such as:

```
elasticsearch:
            host: elasticsearch-elasticsearch-cluster.default.svc.cluster.local
            port: 9200
```

But other than that, I'm not seeing a compelling case for an EndpointCatalogue based on our current design, especially for airshipctl. I'd definitely welcome additional opinions, since it's possible I've missed something.

**Comment by mf4716** [comment]
@matthew-fuller  - Matt, is there an update?  Are we close(r) to finishing?

**Comment by matthew-fuller** [comment]
Closing this issue, and opening a new one in treasuremap to create an endpoints catalogue that can accommodate the airship/charts endpoint format. This will likely be targeted for future release.
