### ISSUE TITLE
Incorporate HWCC into the deployment gate.

### ISSUE THREAD

**Issue by Ashughorla** [airshipit/airshipctl#326]
Please provide any user guide for this task if any else steps to be followed.

**Proposed change**
We like to incorporate Hardware classification controller into deployment gate.

**Potential impacts**
No potential impact.

**Comment by digambar15** [comment]
@mattmceuen can you profile any doc/resource on how to integrate HCC in deployment gate ?

**Comment by mattmceuen** [comment]
@digambar15 I think a good place to start would be to piggyback on top of the existing deployment gate scripts, so that HWCC is tested as part of a normal deployment.  Perhaps

1) define a couple of profiles inside the test-site site, one that we expect will match all the (nested VM) hosts, and another one we expect to match none of the hosts.  The profiles could have something like "a very small minimum amount of ram" and "a huge minimum amount of ram", respectively.
2) add a new script to airshipctl/deployment which runs after everything else, and only succeeds if all hosts match the expected profile, and none of the hosts match the unexpected profile.

How does that sound to you?

**Comment by digambar15** [comment]
Perfect! Liked the approach. Will work on it and submit the upstream patch at earliest after our internal testing.

**Comment by Ashughorla** [comment]
@mattmceuen @dukov 
Patchset raised. Kindly review.
https://review.opendev.org/#/c/748421/

**Comment by Ashughorla** [comment]
@mattmceuen @roman
Updated the patchset according to review comments.
https://review.opendev.org/#/c/748421/

**Comment by Ashughorla** [comment]
@gorshunov
Kindly review changes. Updated patchset.
https://review.opendev.org/#/c/748421/

**Comment by Ashughorla** [comment]
@mattmceuen @gorshunovr 
Kindly review patchset https://review.opendev.org/#/c/748421/
Done with changes suggested by community.

**Comment by Ashughorla** [comment]
@mattmceuen 
Kindly review patchset https://review.opendev.org/#/c/748421/
Done with changes suggested by you.

**Comment by Ashughorla** [comment]
We are done with changes as suggested.
Kindly review.

@mattmceuen @dukov

**Comment by Ashughorla** [comment]
@dukov 
Kindly provide code-review at https://review.opendev.org/#/c/748421/14
Just done rebase.

**Comment by Ashughorla** [comment]
Patchset is merged.
