### ISSUE TITLE
Ethernet_mac_address get null value if mac address is not passed in host catalogue causing network service to fail.

### ISSUE THREAD

**Issue by sb464f** [airshipit/airshipctl#404]
**Describe the bug**
Host-generator template is generating a null value like below when host catalogue is not having any mac value for the interface
```
-
  id: enp94s0f1
  mtu: "9100"
  name: enp94s0f1
  type: phy
  
  ethernet_mac_address: <no value>
```
which is causing network service to come up and logs says, `failed to rename  mac=<no value> `.

**Steps To Reproduce**
skip passing any value to ethernet_mac_address rebuild ephemeral iso with no value.

**Expected behavior**
Expected to not pass key `ethernet_mac_address` when host catalogue is not passing any value. like below

```
-
  id: enp94s0f1
  mtu: "9100"
  name: enp94s0f1
  type: phy
```

**Comment by mattmceuen** [comment]
Hey Sai, the template will skip over `ethernet_mac_address` if the catalogue doesn't have `macAddresses` defined:
https://github.com/airshipit/airshipctl/blob/master/manifests/function/hostgenerator-m3/hosttemplate.yaml#L85-L87

Can we just leave `macAddresses` out of the catalogue if we don't want to render any?  Or is there a use case where an empty (but present) `macAddresses` would be useful -- we can add logic for that if so.

**Comment by mattmceuen** [comment]
said differently, right now the generator is a passthrough - if macAddresses is null in the catalogue, ethernet_mac_addesses will be null in the BMH.  It's better to keep the generator a passthrough except when there is good reason do diverge (since that's more code to maintain) -- that's why I was asking about the use case.

**Comment by sb464f** [comment]
Okay if we can skip `macAddresses`. I ran into a scenario where I wanted to pass eno4 macaddress and skip all other interfaces mac addresses. Only for those kind of scenarios.

**Comment by mattmceuen** [comment]
I think passing a subset of mac addresses ought to work fine - i.e. only eno4.  If that doesn't work as expected let me know though.

**Comment by mattmceuen** [comment]
Just re-read your response @sb464f and now I understand the issue -- I agree that it makes sense to be able to pass one mac address for one interface but leave out mac address for another interface, if that's a real use case you were hitting.  I'll add that logic to the template!

**Comment by sb464f** [comment]
Yes that is the use case @mattmceuen want to add eno4 mac address and leave out other interfaces.

**Comment by mattmceuen** [comment]
@sb464f  just for curiosity's sake, what was the driver for this use case?  I'd like to better understand when the mac addresses are needed and when they're not.

Note to self: also consider add validation logic so that if there's en entry under macAddresses/ipAddresses that does not correspond to a defined network interface, throw an error.

**Comment by mattmceuen** [comment]
I lost track of this.  The work needed for this is to adjust the hostgenerator function template to *contitionally* set the ethernet_mac_address, only when the catalogue has a value defined for it, rather than blindly copying in the value from the catalogue (even when the value is missing).

**Comment by sirajyasin** [comment]
@lb4368 , i can work on this issue. Can you please assign this to me
