### ISSUE TITLE
Plugin Release Management

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#429]
**Proposed change**
Related to #419, need to develop a Release Management process for the kustomize plugins in airshipctl.

Per 12/7/2020 design discussion (https://hackmd.io/6hw3pJOUT7iNsEceovABgA#Discuss-Replacement-Transformer-Image-Versioning-YAML-Call-perhaps):

- Create a tag for each plugin , i.e. v1.0
- Plugin tag would be used across artifacts using the plugin (e.g. ReplacementTransformer)
- Expectation is that plugins will change infrequently, and, therefore, image definition in manifests could be done manually.

**Comment by seaneagan** [comment]
Since we'll be implementing standalone versioning for each krm function, we'll need a strategy for how to organize this in git. I see two options:

1. separate git repos e.g. github.com/airshipit/replacement-transformer with e.g. a v1.0.0 tag.
2. separate git tag/branch "namespaces" within github.com/airshipit/airshipctl repo e.g. replacement_transformer-v1.0.0 tag and replacement_transformer-v1.0 branch

For now I'll go with 2. since it is the path of least resistance, if we want to migrate to 1. at any point that should be fairly straightforward, just means potential overhead of creating opendev repos / mirroring to github.

Regardless of the solution to #419 it would be nice to minimize the frequency of updating the version tags. To accomplish this, we can reuse the version tag strategy used by many container images, which is to maintain moving tags for major and minor versions in addition to the static tag for each individual version e.g. for v1.2.3 we also push v1.2 and v1 tags. This means we can pin to v1 and only need to update when breaking changes are introduced i.e. v2. There is support for the this pattern [here](https://github.com/elgohr/Publish-Docker-Github-Action#tag_semver) but unfortunately that won't work with option 2. above as it wouldn't know to strip the prefix from the git tags, but perhaps we could just implement the calculation of the semver tags directly in bash.

**Comment by seaneagan** [comment]
https://review.opendev.org/c/airship/airshipctl/+/762924

**Comment by seaneagan** [comment]
Above patchset has merged, closing. #419 covers the usage of these releases.
