### ISSUE TITLE
Allow airshipctl phase render to display encrypted secrets

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#453]
**Problem description**
If a user does not have access to the secret encryption keys and they attempt to run a phase render for a document set that contains encrypted secrets, the phase render fails.

**Proposed change**
Rather than fail, phase render should display the secrets in their encrypted format.

**Potential impacts**
Given the secret data remains encrypted, there should not be any security impacts.

**Comment by aodinokov** [comment]
@ak3216 , looks good. please assign it to me

**Comment by jezogwza** [comment]
Modify airshipcctl to support the following flags:

- flag indicates dont fail if decryption fails https://github.com/airshipit/airshipctl/issues/453 of lack of keys
.....

**Comment by aodinokov** [comment]
The PoC work has been done in manifests [1] and in sops plugin [2]. Will need to wait for the sops plugin PR to be merged.
In case of any issues I have a plan B, that will work in a bit different way, but it may be implemented with the current sops function version.

>@aodinokov, @jezogwza does this look right to you?

I think its good. that changes to airshipctl will be minimal

[1]
https://review.opendev.org/c/airship/airshipctl/+/772467/2/manifests/site/test-site/target/generator/results/decrypt-secrets/configurable-decryption.yaml
[2]
https://github.com/aodinokov/kpt-functions-catalog/commit/f396af273cd70607796d66153d3c69ca8152b8d0

**Comment by aodinokov** [comment]
@mattmceuen maybe we should do vise-versa. we need to create a flag DONT_TOLERATE_DECRYPTION_FAILURES and use it in phase run. these commands need that because kubeconfig is a secret and it has to be encrypted/decrypted. and kubeconfig is part of bundle with phases.
That's because probably airshipctl phase list, plan list and other commands shouldn't fail.
alternatively we'll need to pass TOLERATE_DECRYPTION FAILURES in all commands we want to make work without env variables...

will think about that more

**Comment by aodinokov** [comment]
implemented in https://review.opendev.org/c/airship/airshipctl/+/773730

**Comment by aodinokov** [comment]
the remaining part is in https://review.opendev.org/c/airship/airshipctl/+/775737

**Comment by aodinokov** [comment]
https://review.opendev.org/c/airship/airshipctl/+/775737 has been merged and can be closed

**Comment by ak3216** [comment]
Closing per code merge
