### ISSUE TITLE
Airshipctl containers are no longer tagged with git commit hash

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#490]
Up until 16 days ago, airshipctl container builds would be tagged with commit hash when they are pushed to quay.io.  Now, although the image is still pushed, it's no longer tagged with the commit, making it difficult to correlate git commits to particular image builds.  We should get this working again.

https://quay.io/repository/airshipit/airshipctl?tab=tags

**Comment by raliev12** [comment]
@mattmceuen Who has the admin rights to airshipit space in quay.io? It seems this issue is related to permissions. 
As you can see from [build history](https://zuul.opendev.org/t/openstack/builds?job_name=airship-airshipctl-publish-image), this job started to fail after new krm function introduction in [this commit](https://review.opendev.org/c/airship/airshipctl/+/774350). If you take a look at errors, the job tries to push cloud-init image to quay.io/airshipit/cloud-init, but receives an error **unauthorized: access to the requested resource is not authorized**, therefore the whole job fails. I think it might be helpful to check airshipit/cloud-init repo permissions.

**Comment by jezogwza** [comment]
Can close this was a bug that was fixed. 
Cloud init image wasn't properly pushed to quay repo. This ended up been a permission issue.
