### ISSUE TITLE
Upgrade Kustomize to the latest version

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#601]
**Problem description**
In an effort to keep Airship current with the latest updates of its supporting components, upgrade Kustomize to the latest version (currently v4.2.0) 

Kustomize information can be found here: 
- https://kustomize.io/
- https://github.com/kubernetes-sigs/kustomize/
- https://github.com/kubernetes-sigs/kustomize/releases

**Proposed change**
- Upgrade Kustomize to v4.2.0
- Validate Kustomize still functional & resolve any breaking changes

**Comment by aodinokov** [comment]
Here is what we can do:

The main issue with 4.1.3 and further (4.2.0) is that there will be conflicting dependencies.
I elaborated on that some time ago [here](https://hackmd.io/QiEksO4fRk-MnBjwBFaAkQ#Upgrade-to-kustomize-413-issues-Alexey-O). here is another PR https://review.opendev.org/c/airship/airshipctl/+/788582 that worked some time ago, but since we were not going in that direction it is in merge conflict now.

That means if we want to update only kustomize - we can update it only till 4.1.2, like it's done here:
https://review.opendev.org/c/airship/airshipctl/+/794269 . This PR is ready to be merged if needed.

if we want to keep up with the latest kustomize (which is a good idea for many reasons :) ), we can proceed in another way:
we need to get rid of ClusterApi dependency first by moving all clusterapi operations to krm-function (see Ruslan's PR: https://review.opendev.org/c/airship/airshipctl/+/793701 - it works already). 
Once clusterApi disappears it will be possible to bump dependencies much more easily.

**Comment by ak3216** [comment]
Just to note, for patchset 793701, the corresponding issue is #568. Assuming we proceed that way, once merged & we close #568 then we can proceed with this issue.

**Comment by aodinokov** [comment]
@ak3216 , right... I've rebased 794269 on top of 793701 (made a separate PR: https://review.opendev.org/c/airship/airshipctl/+/800722 - it's in WIP, but looks like at least airshipctl can be compiled with new dependencies including kustomize)

**Comment by aodinokov** [comment]
https://review.opendev.org/c/airship/airshipctl/+/800722 is on top of 793701. it's complete and green. need to merge 793701, and rebase it and merge

**Comment by aodinokov** [comment]
done in https://review.opendev.org/c/airship/airshipctl/+/800722 . We have kustomize 4.2.0 now. Can be closed.

**Comment by aaronsheffield** [comment]
Closing based on the above merge.
