### ISSUE TITLE
Validate and Compare Expected Hardware Configuration for BM hosts

### ISSUE THREAD

**Issue by digambar15** [airshipit/airshipctl#64]
****Problem description (if applicable)****
 Validate and Compare Expected Hardware Configuration -
Story AIR-79 - Implement feature in Airship for expected Hardware Configuration.
We had discussion with Airship community in the past and decided to implement feature in Metal3 first as Airship side framework will be implemented later on, after base level feature ready in Metal3.
Submitted proposal to Metal3 - https://github.com/metal3-io/metal3-docs/pull/60.

**Proposed change**
After having multiple discussions with Metal3 core reviewer team, we came to conclusion that instead of implementing feature in BMO, we should implement new CRD for HW expected  configuration. We have implemented entire CRD on under Metal3 repo and currently we are actively contributing to it - https://github.com/metal3-io/hardware-classification-controller

There are two level of support to be addded for this feature - 
1. South Bound (which is Hardware Classification Controller)
	- Currently basic support for this feature is ready.
2. North Bound (Build a mechnism to talk to HCC and BMO)
	- Now it's time to introduce mechnism in Airship to add support for Hardware Classification Controller (HCC).
	- We will have to design YAML for HCC and BMO.

**Potential impacts**
It doesn't have any impact on Metal3/BMO.

**Comment by pramchan** [comment]
We need split this into two issues , one  for North Bound and another for South Bound APIs.
The priorities in that case SB one would be focus of metal3.io with label requirements from client 
calling metal3.io. Since the work is going to be done in metal3.io this issue will contain URL or links to work being done there.
JT
The NB issue is being worked on as part of AirshipCTL filtering documents for BM host selection.
Prakash

**Comment by drewwalters96** [comment]
Any updates on this? This is not really an airshipctl issue and should probably be tracking in the metal3-io repo.
